version: "3.8"
services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"    # Kafka broker
      - "9644:9644"    # Admin API (internal)
    environment:
      - REDPANDA_AUTO_CREATE_TOPICS=true
    volumes:
      - redpanda-data:/var/lib/redpanda
  redpanda-console:
    image: redpandadata/console:latest
    container_name: redpanda-console
    ports:
      - "8080:8080"    # Web UI
    environment:
      - REDPANDA_BROKERS=redpanda:9092
    depends_on:
      - redpanda

  transaction-api:
    build:
      context: ./transaction-api
    depends_on:
      - redpanda
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"

  fraud-frontend:
    build: ./frontend
    container_name: fraud-frontend
    ports:
      - "8082:80"
    depends_on:
      - transaction-api

  fraud-worker:
    build: ./fraud-worker
    depends_on:
      - redpanda
      - postgres
    environment:
      REDPANDA_BOOTSTRAP: ${REDPANDA_BOOTSTRAP}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  postgres:
    image: postgres:15
    container_name: fraud-platform-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - fraud-platform_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  redpanda-data:
  fraud-platform_pgdata:
